version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ulchecker-backend:latest
    container_name: ulchecker-backend
    ports:
      - "8080:8080"
    networks:
      - ulchecker-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ulchecker-frontend:latest
    container_name: ulchecker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ulchecker-network
    restart: unless-stopped

networks:
  ulchecker-network:
    driver: bridge 